default_env: &default_env
  working_directory: ~/repo
  docker:
    - image: reactnativecommunity/react-native-android

build_steps: &build_steps
  steps:
    - checkout
    - run: npm i -g envinfo && envinfo
    - run: npm install
    - run: npm run test

version: 2.1
jobs:
  build:
    <<: *default_env
    <<: *build_steps
  android_delivery:
    <<: *default_env
    <<: *build_steps
    steps:
      - run: cd android && ./gradlew clean && ./gradlew assembleRelease
      - store_artifacts:
          path: android/app/build/outputs/apk/release

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  generate_apk:
    jobs:
      - android_delivery:
          type: approval
          filters:
            branches:
              only: master
